### ISSUE TITLE
Allow to use smart contract for validator set, as in parity

### ISSUE THREAD

**Issue by blazejkrzak** [lukso-network/pandora-execution-engine#30]
Implement the smart contract valiudator set function, like in parity

Meaning that the validator set can be read from a consensus smart contract, and change over time, rather than be fixed from the genesis.json only

This should work the same as in parity, and the functions called internally on the smart contract should be the same as in parity

**Backstory:**
There are some tricky things to consider:

- [ ] if validators list that will come from smart contract must have same length each epoch

- [ ] count if block was valid on epoch transition (additional layer of complexity)

**Comment by blazejkrzak** [comment]
To acheive that wee need to look up into `stateDB`

Little description about stateDB
```
// StateDB structs within the ethereum protocol are used to store anything
// within the merkle trie. StateDBs take care of caching and storing
// nested states. It's the general query interface to retrieve:
// * Contracts
// * Accounts
```

**Comment by atif-konasl** [comment]
Need to implement validator set contract for Aura engine for sealing block using dynamically updated validator set. We can update validator set dynamically using smart contract and can avoid any downtime of the network.

algorithm -
- first initiate validator list from genesis.json file with latest validator set selection mode. If lastly the node gets validator list from smart contract then it initiates the validator set contract and get validator list from contract.

- After each block finalization, aura engine check transition event. If there will be a transition in next block then engine setup for this transition and update the validator list. The same execution happens when any block is downloaded or propagated.

- Any addValidator or removeValidator method call transaction comes from externally to geth client, node will check weather or not this transaction is related to the validator set contract. Then node will update the the contract's storage and call finalizeChange method using SYSTEM_ADDRESS. State trie root will be updated with transaction as well as node's finalizeChange method call. 

- After calling finalizeChange method, engine gets updated with new set of validator list.

Implementation details -
To communicate with smart contract from geth client, there is two option - RPC client and simulated backend client. RPC client is not suitable for communicating internally and it is used for remote call. Another way is simulated backend which has same list of apis but they are implemented for internal call to smart contract. So, started implementation with simulated backend and generate validator set contract abi using abigen. Implemented all related api for interacting with validator set contract and integrated with aura engine.
